### ISSUE TITLE
prevent matplotlib error

### ISSUE THREAD

**Issue by sfreund-DLR** [sfreund-DLR/tankoh2#69]
in tankoh2.service.plot.muwind line 29

Replace [tight layout](https://matplotlib.org/stable/tutorials/intermediate/tight_layout_guide.html#)
> fig.tight_layout()

with something more useable. 

- Maybe there are other options to tight layout
- or use a fix layout using [subplots_adjust](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots_adjust.html). you can play with the parameters when the plot is shown (in tankoh2.design.designopt line 296)

**Comment by jacolinu** [comment]
One option may be to split the legend into multiple columns once they get too long (at about 25 entries).
This picture shows how that would look (in this case, new columns are created after 3 entries instead of 25, to test the program more quickly). 
![grafik](https://user-images.githubusercontent.com/118367442/206445570-07584e6a-6f49-4381-8020-cdc2bdb672e4.png)
Of course, with 300 layers, this would eventually lead to other problems, with the pictures becoming too wide to be usable. Of course, in this case the legend is very useless anyway, since the colors cannot be differentiated. Maybe another option would be to show in the legend only the 25 most recent layers? Or how about showing only the most stressed layers in the legend (and put the others in grayscale).

**Comment by jacolinu** [comment]
Solution in Branch tankoh2-69, showing only 10 most recent layers in color and with legend entries, older ones in black.
What do you think?
![grafik](https://user-images.githubusercontent.com/118367442/207329006-615a25bb-0a68-484e-a091-db58206c832a.png)
Maybe the width of the entire plot could also be increased for better readability.
(Note: for the final plot output of an optimization run, this is not yet implemented because that plot doesnt use the plotPuckAndTargetFunc() function in muwind)

**Comment by sfreund-DLR** [comment]
cool!
is it also possible to include the first 2 layers in color and in the legend?

**Comment by jacolinu** [comment]
That's possible, but because the layer lines are drawn over each other in order, the first layers will be hidden under newer lines.

**Comment by sfreund-DLR** [comment]
due to bending, I expect, the first lines to be the ones with maxima at important locations
