### ISSUE TITLE
check tankoh2 isotensoid implementation

### ISSUE THREAD

**Issue by sfreund-DLR** [sfreund-DLR/tankoh2#76]
check the existing implementation. 

- e.g. atheat3 causes a liner mass of 1e59 in control_winding (getLinerMass(linerTankoh, linerThickness=linerThk))
- create a test for this geometric case
- correct the error

**Comment by jacolinu** [comment]
The error results from the getContour method of the class DomeIsotensoid. (dome.py line 1115)
Under certain conditions, if the check "while alpha < np.arctan(np.sqrt(2))" is not fulfilled, ending the loop,  the iterable phi grows to pi/2, giving very large rm due to division by 0 (line 1141). The values for x and r returned by the method become incorrect.

**Comment by jacolinu** [comment]
Should be fixed with [1c3c471](https://github.com/sfreund-DLR/tankoh2/commit/1c3c471b5c04069fd5d044535d94b6161b6b5344)

One other thing I noticed was that the implementation of properties such as volume of a dome or liner are inefficient because they are recalculated every time they are requested (which also includes rebuilding the contours multiple times). However, it doesn't impact the runtime because it isn't used in the optimization loop.
